### PR TITLE
chore(trezor): Update to Trezor Connect v9

### PR DESCRIPTION
**Pull request by sime**
Hello from Trezor!

We are preparing a GA release of Trezor Connect v9.

Wanted to see if you tests pass with the new version, though I'm uncertain if the tests actually test anything Trezor Connect releated.

### CODE REVIEW

**Comment by kvhnuke** [comment]
@Hannsek and @sime thanks! we will go ahead and test it out

**Comment by kvhnuke** [comment]
we will include this in a future release!

**Comment by kvhnuke** [comment]
added in #149

**Comment by sime** [comment]
Hi @kvhnuke 

Looks like you did a minor upgrade to Trezor Connect and are still using v8.

V9 is actually a new package: @trezor/connect.

**Pull request closed without merging**
