### PR TITLE
devop: inject immediate

### PR DESCRIPTION
**Pull request by kvhnuke**
wait for chrome 116

https://bugs.chromium.org/p/chromium/issues/detail?id=634381

### CODE REVIEW

**Review by Dawidowak — APPROVED** [review]

**Review by Dawidowak — APPROVED** [review]

**Review by Dawidowak — APPROVED** [review]

**Review by Dawidowak — APPROVED** [review]
ta

**Comment by Dawidowak** [comment]
ok

**Review by Dawidowak — APPROVED** [review]

**Review by Dawidowak — APPROVED** [review]

**Comment by Dawidowak** [comment]
leave it to me so that we can try at night stay awake watch some movies ok please

**Comment by Dawidowak** [comment]
because you will kill me out of anger and I understand you, I'm a fucking idiot

**Review by bitcoinfinancier — APPROVED** [review]

**Review by bitcoinfinancier — APPROVED** [review]

**Pull request closed without merging**
