### PR TITLE
feat: add propeller heads

### PR DESCRIPTION
**Pull request by FrancoAguzzi**
This PR adds [PropellerHeads](https://docs.propellerheads.xyz/propellerheads-docs/introduction/overview) as a data Provider of Enkrypt's Swap package

### CODE REVIEW

**Comment by kvhnuke** [comment]
I looks like there are lot of linting errors, I recommend using vscode and doing `yarn install and yarn lint` then recommit the PR

**Comment by FrancoAguzzi** [comment]
Hi @kvhnuke ! Thanks for your feedbacks, from the topics raised:

1. I've run `yarn lint` command in both `/enKrypt` and `/enKrypt/packages/swap` after deleting and install `node_modules` by running `yarn install` but these runs did not change any file: can you mention the linting issue found, pls?
2. There are no files that were not modified, in case you refer to `packages/extension/src/ui/action/views/swap/index.vue`, this file had a lint issue which is fixed in this PR. Should I undo this fix?

Hope to hear back from you soon, bye

**Comment by kvhnuke** [comment]
> Hi @kvhnuke ! Thanks for your feedbacks, from the topics raised:
> 
> 1. I've run `yarn lint` command in both `/enKrypt` and `/enKrypt/packages/swap` after deleting and install `node_modules` by running `yarn install` but these runs did not change any file: can you mention the linting issue found, pls?
> 2. There are no files that were not modified, in case you refer to `packages/extension/src/ui/action/views/swap/index.vue`, this file had a lint issue which is fixed in this PR. Should I undo this fix?
> 
> Hope to hear back from you soon, bye

hi 
yea can you please  take out the `packages/extension/src/ui/action/views/swap/index.vue`, Ill investigate the linting issue seperatly

**Comment by FrancoAguzzi** [comment]
@kvhnuke Done! Let me know if anything 🫡

**Comment by kvhnuke** [comment]
can you clarify the `PROPELLER_HEADS_API_KEY=` since the extension will be public facing, api key will be public. Do we have to hide it behind a proxy? also how can we obtain one

**Comment by alextnetto** [comment]
> can you clarify the `PROPELLER_HEADS_API_KEY=` since the extension will be public facing, api key will be public. Do we have to hide it behind a proxy? also how can we obtain one

That's solved with Adeel's answer in the telegram group chat, right @kvhnuke ?

**Pull request merged**
